services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testNewFeatures
      POSTGRES_DB: doctorwho
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  migrate:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: npx prisma migrate dev --name init
    depends_on:
      - db

volumes:
  pgdata:
